services:
  esp-idf-dev:
    build:
      context: ..
      dockerfile: esp-idf-dev/Dockerfile
    image: mrcodecx/esp-idf-dev:release-v6.0
    container_name: esp-idf-dev
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev
      - ${WORKSPACE}:/workspace
      - ${WORKSPACE}/.docker-data/.claude:/home/ubuntu/.claude
      - ${WORKSPACE}/.docker-data/.claude.json:/home/ubuntu/.claude.json
      - ${WORKSPACE}/.docker-data/.codex:/home/ubuntu/.codex
      - ${WORKSPACE}/.docker-data/.vscode-server:/home/ubuntu/.vscode-server
