services:
  alpine-dev:
    build:
      context: ..
      dockerfile: alpine-dev/Dockerfile
    image: alpine-dev:latest
    container_name: alpine-dev
    stdin_open: true
    tty: true
    volumes:
      - ${WORKSPACE}:/workspace
