services:
  ubuntu-dev:
    build:
      context: ..
      dockerfile: ubuntu-dev/Dockerfile
    image: mrcodecx/ubuntu-dev:noble
    container_name: ubuntu-dev
    stdin_open: true
    tty: true
    volumes:
      - ${WORKSPACE}:/workspace
