services:
  arch-dev:
    build:
      context: ..
      dockerfile: arch-dev/Dockerfile
    image: arch-dev:latest
    container_name: arch-dev
    stdin_open: true
    tty: true
    volumes:
      - ${WORKSPACE}:/workspace
