services:
  node-dev:
    build:
      context: ..
      dockerfile: node-dev/Dockerfile
    image: mrcodecx/node-dev:24
    container_name: node-dev
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    environment:
      - CODEX_HOME=${CONTAINER_HOME}/.codex-data
    volumes:
      - ${WORKSPACE}:/workspace
      - ${WORKSPACE}/.docker-data/.claude:${CONTAINER_HOME}/.claude
      - ${WORKSPACE}/.docker-data/.claude.json:${CONTAINER_HOME}/.claude.json
      - ${WORKSPACE}/.docker-data/.codex-data:${CONTAINER_HOME}/.codex-data
      - ${WORKSPACE}/.docker-data/.vscode-server:${CONTAINER_HOME}/.vscode-server
